//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
import { EntityViewModel } from '../../../view-models/view-models';
import { JobViewModel } from '../../../view-models/view-models';

export
class EntityRouteParametersViewModel
{
    public Job: JobViewModel;
    public JobEntities: EntityViewModel[];
    public Entity: EntityViewModel;
}
